services:

  juice_webapp:
    image: bkimminich/juice-shop:latest
    restart: unless-stopped
    ports:
      - "${LISTEN_PORT:-8080}:3000"
    volumes:
      - ./juice-shop/config:/juice-shop/config